- hosts: localhost
  connection: local
  vars:
     project: ansiblue
     config:
       toolbox: "{{ lookup('template', 'configs/toolbox.yaml') | from_yaml }}"

  tasks:
    - name: Create and configure toolbox
      include_tasks: playbooks/setup/setup.yaml
      tags: [always]
      args:
        apply:
          tags: [toolbox, "{{ toolbox.name }}"]
      loop: "{{ config.toolbox }}"
      loop_control:
        loop_var: toolbox
        label: "{{ toolbox.name }}"
