- name: ic
  image: registry.fedoraproject.org/fedora-toolbox:36
  tasks:
    - tasks/common/install_packages.yaml
    - tasks/common/upgrade_packages.yaml
    - tasks/common/configure_user.yaml

- name: unicamp
  image: registry.fedoraproject.org/fedora-toolbox:36
  tasks:
    - tasks/common/install_packages.yaml
    - tasks/common/upgrade_packages.yaml
    - tasks/common/configure_user.yaml

- name: webdev
  image: registry.fedoraproject.org/fedora-toolbox:36
  tasks:
    - tasks/common/install_packages.yaml
    - tasks/common/upgrade_packages.yaml
    - tasks/common/configure_user.yaml

- name: latex
  image: registry.fedoraproject.org/fedora-toolbox:36
  tasks:
    - tasks/common/install_packages.yaml
    - tasks/common/upgrade_packages.yaml
    - tasks/common/configure_user.yaml
